### PR TITLE
Update 05.04.2020

### PR DESCRIPTION
**Pull request by Vafin84**
Removed extra lines that never existed.

### CODE REVIEW

**Comment by WolverinDEV** [comment]
Out of curiosity, why remove these extra lines?
Dosn't really make sense for me. This means that some messages wouldn't get translated^^

**Comment by Vafin84** [comment]
The thing is, it's not my translation. Where did these lines come from? I think this is machine translation and not mine. This was not in my previous request https://github.com/TeaSpeak/TeaWeb/pull/80/files

**Comment by WolverinDEV** [comment]
Ahh well you're right then.
Yep I just updated all translations via the google translate script to add all new translations ;)

**Comment by Vafin84** [comment]
I think machine translation is not quite correct and leads to errors. I'll slowly bring it to perfection myself)

**Pull request merged**
