### PR TITLE
Portuguese_Language_Update (Part 1)

### PR DESCRIPTION
**Pull request by cyberlimbo**
-Starting the TeaClient PT translation (5% concluded)

### CODE REVIEW

**Comment by WolverinDEV** [comment]
?!

**Comment by cyberlimbo** [comment]
Correct word: "Token"
Incorrect word: "Toke"

Same incorrect word in all translation files.

**Comment by WolverinDEV** [comment]
Any why not one PR?

**Comment by cyberlimbo** [comment]
yeah, sorry for that.
Done! I'll keep the file updated ;)

**Pull request merged**
