### PR TITLE
Add translations

### PR DESCRIPTION
**Pull request by mciochu**

### CODE REVIEW

**Comment by WolverinDEV** [comment]
Hey,
had you done the translation by yourself or had you used the google translations?

**Comment by mciochu** [comment]
I corrected the one that was already done with the google. Almost half of it was incorrect.

**Comment by WolverinDEV** [comment]
Yes thats a general thing :)
May consider to edit the direct main file instead creating a new one?

**Comment by mciochu** [comment]
Yeah, I'm editing an existing.

**Pull request closed without merging**
